servicename: <+service.identifier>
fullimagepath: <+artifacts.primary.image>
version: <+artifacts.primary.tag>
replicas: 1
port: 5000
resourcelimits:
 cpurequest: "100m"
 memrequest: "64Mi"
 path: "/hello"