servicename: <+service.identifier>
fullimagepath: <+artifacts.primary.image>
imagepath: <+artifacts.primary.imagePath>
cpurequest: <+serviceVariables.requestscpu>
memrequest: <+serviceVariables.requestsmemory>